### ISSUE TITLE
Beta 0.9

### ISSUE THREAD

**Issue by kvichans** [kvichans/cuda_find_in_files#38]
Encodings for reading files:
![fif-0 9](https://cloud.githubusercontent.com/assets/7419630/15017968/6d6315e6-1220-11e6-95aa-869c7017bd8d.JPG)
The first suitable from series will be applyed.
My _def encoding_ is "cp1251". For other it may be different.
If _def encoding_ is "UTF-8" then list shrinks to 
![fif-0 9-shr](https://cloud.githubusercontent.com/assets/7419630/15018251/7f19d10c-1221-11e6-8de3-52a77a8d08d9.JPG)
This _def encoding_ can be set in `user.json`

```
    // Exact encoding to read files
    "fif_locale_encoding":"cp1252",
```

It can be usefull for Linux users as _def encoding_ is "UTF-8".

NB! "detected" is slow on large list of files.

**Comment by Andreas123456** [comment]
1. The new encoding stuff works well.
2. Wish: Please bring back the tree type "path/(r:c:l):line". It was the most useful tree type in my opinion.
3. Bug: When you search through *.txt files for "history" in the directory in which CudaText is installed, using the tree type "dir/file(r:c:l):line", you'll get the following result:
   ![04-05-_2016_19-15-22](https://cloud.githubusercontent.com/assets/12023109/15023151/74aaa0e4-122f-11e6-9916-22142b576b33.png)
   The directory <readme> is shown three times in the results. It should be shown only twice. Furthermore, the directories <lang> and <themes> should not be shown at all, because they contain no results.
4. Problem: When using the tree type "dir/file(r:c:l):line", Navigate to source won't work for files in deeply nested directories. In my opinion, you don't need to spend time fixing this problem. You can simply remove the tree type "dir/file(r:c:l):line" (and similar tree types), because they're not useful IMHO.

**Comment by kvichans** [comment]
2) I don't remember such type - "path/(r:c:l):line". But a bug realy was for type "dir/file(r:c:l):line" and in report "file" was skipped.
4) Pls pass me report with nav problem

**Comment by Andreas123456** [comment]
> 2) I don't remember such type - "path/(r:c:l):line".

I mean the type from the following old screenshot:

![1b48fc98-0b28-11e6-8a7c-99632ed77256](https://cloud.githubusercontent.com/assets/12023109/15029082/52735bd4-124c-11e6-97a7-56ff80185f2e.png)

> 4) Pls pass me report with nav problem

To reproduce the problem, first create the following directory structure:

1/2/3/txt

Then copy the following file into the sub-directory txt:

[test.txt](https://github.com/kvichans/cuda_find_in_files/files/249582/test.txt)

Then do a search with the following settings:

![04-05-_2016_22-59-50](https://cloud.githubusercontent.com/assets/12023109/15029300/3a78dcf6-124d-11e6-8717-147788badd8c.png)

You will get the following results:

![04-05-_2016_23-00-56](https://cloud.githubusercontent.com/assets/12023109/15029348/6907ab06-124d-11e6-8eb1-9538f7da6e25.png)

Put the cursor on line 4 and then Navigate to Source ==> nothing will happen.

Here is the results file:

[results.txt](https://github.com/kvichans/cuda_find_in_files/files/249592/results.txt)

**Comment by kvichans** [comment]
3) 4) I see both problems and one reason - "skipped dir" in report tree: `data/lang` in (3), `2/3` in (4)

**Comment by kvichans** [comment]
fixed: (3), (4)

**Comment by Alexey-T** [comment]
@samdark Maybe u interested in find-in-files?
